parameters:
    contentonthefly.controller.location.class: EzSystems\EzContentOnTheFlyBundle\Controller\LocationController

services:
    contentonthefly.controller.location:
        class: '%contentonthefly.controller.location.class%'
        arguments:
            - '@ezpublish.api.repository'
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.content_type'
            - '@ezpublish.api.service.content'
        calls:
            - [setConfiguration, ['$content;content_on_the_fly$']]
            - [setLogger, ['@?logger']]
